from typing import Optional, Dict, Tuple

class TlfuCore:
    def __init__(self, size: int): ...
    def create(self, key: str, expire: int) -> Tuple[int, Optional[str]]: ...
    def update(self, index: int, expire: int): ...
    def remove(self, index: int): ...
    def access_by_str(self, key: str): ...
    def access_by_index(self, index: int): ...
    def advance(self, now: int, cache: Dict, kh: Dict, hk: Dict): ...

class LruCore:
    def __init__(self, size: int): ...
    def create(self, key: str, expire: int) -> Tuple[int, Optional[str]]: ...
    def update(self, index: int, expire: int): ...
    def remove(self, index: int): ...
    def access_by_str(self, key: str): ...
    def access_by_index(self, index: int): ...
    def advance(self, now: int, cache: Dict, kh: Dict, hk: Dict): ...

class BloomFilter:
    def put(self, key: str): ...
    def contains(self, key: str) -> bool: ...
